### ISSUE TITLE
Create test file

### ISSUE THREAD

**Issue by zachary-trudo** [zachary-trudo/go-api-examples#19]
As a developer I'd like to have a test tasks.csv and a test script that tests our server API.

Each api call should be tested:
- Add
- Remove
- Search by keyword
- Search by date/time
- List

We can either do this in python or go. If Zach does it - it'll be in python.

**Comment by kindermoumoute** [comment]
I agree with the test, but I suggest we don't add this feature for tomorrow. I'm not sure how far Tom wanna make us go with that project.
