### ISSUE TITLE
Get to Beta

### ISSUE THREAD

**Issue by zachary-trudo** [zachary-trudo/go-api-examples#8]
In order to get to Beta we'll need the following functionality:
- Add a task
- Remove a task
- Search for a task
- Display all tasks.

**Comment by kindermoumoute** [comment]
We shouldn't pass the datas in the path of the request. This is what we shouldn't do:

``` curl
curl -XGET "http://localhost:8080/search/meeting/MM-DD-YYYY"
```

Instead we can send it in JSON that way:

``` curl
curl -XGET "http://localhost:8080/add" -d' { "search":"meeting", "before":"MM-DD-YYYY"}'
```

To get this JSON datas in Go you have to play with the `request *http.Request` argument of your handler. In the example above it would be:

``` Go
type Search struct {
    Word            string `json:"search"`
    TimeBefore      time.Time `json:"before"`
}

func SearchTask(respWriter http.ResponseWriter, request *http.Request, _ httprouter.Params) {
    var myDatas Search
    body, err := ioutil.ReadAll(request.Body)
    if err != nil {
        fmt.Println(err)
    }
    err = json.Unmarshal(body, &myDatas)
    if err != nil {
        fmt.Println(err)
    }
    // do your stuff with myDatas
}
```

**Comment by zachary-trudo** [comment]
Did we decide on whether checkedout was going to be true/false or 0/1?

Currently I'm working off the assumption that the csv will look like this:
1,0,YYYYMMDDHHMM,YYYYMMDDHHMM,"Wake up and go to work"
2,0,YYYYMMDDHHMM,YYYYMMDDHHMM,"Stay awake at work"
3,0,YYYYMMDDHHMM,YYYYMMDDHHMM,"Go Home"
