### ISSUE TITLE
Don't edit the csv simultaneously

### ISSUE THREAD

**Issue by kindermoumoute** [zachary-trudo/go-api-examples#9]
As a user I want to send more than 1 request in the same time to my API.

**Comment by zachary-trudo** [comment]
I actually have a question - do we want to be editing the csv with every request anyway? File I/O is incredibly slow.

Perhaps we should open the csv at the beginning and pass the file buffer around instead? Just a thought.

**Comment by kindermoumoute** [comment]
We don't need a csv file until we stop the server - or we can generate the csv every minutes.

But even if we modify the datas in the RAM we need a mutex ressource to avoid simultaneous access.

**Comment by zachary-trudo** [comment]
I think we can mark this as successfully done.

I've looked over all current code and corrected anything that didn't lock/unlock.
